### ISSUE TITLE
Having a stubfile breaks the database connection

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-testsession#60]
When using a stubfile on `silverstripe/testsession` 2.2 `TestSessionHTTPMiddleware` forces a reconnect to the database which seems to switch to the wrong database. It seems to already be connected to the correct database because commenting out these lines [these lines](https://github.com/silverstripe/silverstripe-testsession/blob/2/src/TestSessionHTTPMiddleware.php#L83-L86) keeps the connection to the test database. Oddly this issue did not occur when using SilverStripe 3 it has only cropped up since moving to SilverStripe 4.

**Comment by maxime-rainville** [comment]
Could you clarify what you mean by "stubfile"?

**Comment by dnsl48** [comment]
@UndefinedOffset thank you for taking time to report the issue.
To help me investigate the issue could you please give a little bit more details.
Particularly interesting moments are:
- What is the `wrong database` in your description. Is it another temporary db, or the default one from the configuration?
- What is the `correct database`? Is it the temporary db?

Ideally it could be very helpful if you could also provide a `way to reproduce the issue`, `what's your expected behaviour` and `what is the actual behaviour`.

Thank you!

**Comment by UndefinedOffset** [comment]
So the "wrong database" would be the default one from the configuration (the one my .env file specifies) and the "correct one" would be the temporary database. As for a way to reproduce the issue in one of my Behat context's I have:

```php
class FeatureContext extends SilverStripeContext {
    protected $stubCodeWriter;
    
    /**
     * Initializes context.
     * Every scenario gets it's own context object.
     *
     * @param array $parameters Context parameters (set them up through behat.yml)
     */
    public function __construct(array $parameters=null) {
        parent::__construct($parameters);
        
        //Init the stub code writter
        $this->stubCodeWriter=Injector::inst()->get(TestSessionStubCodeWriter::class);
    }
    
    /**
     * @BeforeScenario
     */
    public function initTestSessionStubCode() {
        $this->stubCodeWriter->write('if(!defined("BEHAT_TEST_SESSION")) {define("BEHAT_TEST_SESSION", true);}');
    }
    
    /**
     * @AfterScenario
     */
    public function resetTestSessionStubCode() {
        $this->stubCodeWriter->reset();
    }
    
    /**
     * @AfterScenario @mobile
     */
    public function afterScenarioMobile(AfterScenarioScope $scope) {
        $this->afterScenarioDesktop($scope);
    }
    
    public function getTestSessionState() {
        return array_merge(
                            parent::getTestSessionState(),
                            array('stubfile'=>$this->stubCodeWriter->getFilePath())
                        );
    }
}
```
Using this code it ends up writing the stubfile which is intern picked up by testsession at which point it tries to connect to the database specified in `.env` even though it's already connected to the temporary database. If you comment out the `getTestSessionState` method the stubfile is not written and the site stays connected to the temporary database.

Does that help?

**Comment by dnsl48** [comment]
Yes, that helps, thank you!

**Comment by UndefinedOffset** [comment]
@dnsl48 are you thinking the simple/correct solution maybe to just remove the `DB::connect()` call in [TestSessionHTTPMiddleware](https://github.com/silverstripe/silverstripe-testsession/blob/2/src/TestSessionHTTPMiddleware.php#L83-L86). Since it already seems to be connected to the temporary database? It also seems a bit redundant to have those lines since they would only apply when a stubfile is used and the stubfile also isn't loaded until after it connects.

If so I could open a pull request to remove those lines.

**Comment by UndefinedOffset** [comment]
One pull request, this seems to work with my scenario.

**Comment by dnsl48** [comment]
Thank you for the contribution!
It should be in the version `2.2.2`.
