### ISSUE TITLE
Any chance of a 2.2.3 or 2.3.0 release?

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-testsession#67]
The current module doesn't seem to work without @pjayme's fix (#66), and you can't pull in `dev-2` to get the fix in the meantime because Composer doesn't see that as a valid development branch (presumably because it's numerical?)

Thanks!

**Comment by madmatt** [comment]
At the moment, this makes the module unusable on 4.3+, because you also can't use `dev-master#0c479ad2eb6ff3729719bbc7c8e578064d916703 as 2.2.2` for example, because it looks at the `HEAD` of `master` which requires `silverstripe/framework: ^5`.

**Comment by dnsl48** [comment]
2.3.0 is here. Can you try it out?

**Comment by madmatt** [comment]
Fantastic, thanks @dnsl48!
